@startuml

left to right direction

Title Use Case diagram

' ======= the actors =========

actor User as "User"

Organisation --|> User

rectangle DB as "Database"

rectangle "Population Stats Application" {


    ' ====== the use cases =========

    usecase UC1 as "Create a report \n for population of \n countries"
    usecase UC2 as "Create a report \n for population of \n cities"
    usecase UC3 as "Create a report \n for population of \n capital cities"
    usecase UC4 as "Create a report \n for population of \n cities and non cities"
    usecase UC5 as "Create a report \n for spoken languages"


    User -- UC5
    User -- UC4
    User -- UC3
    User -- UC2
    User -- UC1

    UC1 -- DB
    UC2 -- DB
    UC3 -- DB
    UC4 -- DB
    UC5 -- DB


}

@enduml